### ISSUE TITLE
Problems after Sailfish OS upgrade

### ISSUE THREAD

**Issue by ninepine** [munkki84/SailFreeCell#1] opened 2014-10-28 07:28 UTC
This is a great implementation of Freecell but after the opt in OS upgrade there are times when it is impossible to move cards. This is because the moved cards won't remain where they were placed even though the move is valid.
This means that the game reaches a point where it can no longer be played.
Has anyone else experienced this with OS 1.1.xx?

**Comment by thebat137** [comment] 2014-10-30 02:42
I originally left this as a comment in the Jolla store, since I failed to expand the description and discover the link to here, but I think I know what the bug is.

I was poking around in the QML and I determined that what seems to be happening is if you drag one card over another card that it can't be dropped on (even if you don't try to drop it), the target card gets the signal that a card has been dragged over it but never gets the signal that the dragged card has been removed.  As a consequence, it thinks there's still a drag in place and won't accept any new incoming drags, so you can't initiate the process of placing a card that _does_ fit in that spot.

You can see this by dragging a card around and watching closely --- as it passes over each possible wrong target card the outline of the target will turn slightly greyer (indicating a "drag" entry), and then never turn black again no matter what you do (because it doesn't receive the "drag" exit).  If you move the cards very carefully, avoiding passing over any other cards en route from source to destination, you can avoid putting any cards in this state and play the game successfully for a while longer, until you inevitably screw it up because your motor control just isn't _that_ perfect.

I think the cause _may_ be this bug in Qt: 
https://bugreports.qt-project.org/browse/QTBUG-39453

AIUI, the Uitukka update moved Sailfish to Qt5.2 from whatever it was before.  The bug is only listed as affecting Qt5.3, but it's not clear whether it might affect earlier versions as well.  It seems to fit the described behavior, and the timing is right, so it strikes me as a good candidate.  If it is indeed this bug, then probably there's not a lot that can be done from the app author's side except implement a complicated workaround and/or agitate for Jolla to push a bugfix.

I created a Together question on this, so maybe if it gets enough upvotes, the Jolla devs will fix it quickly:

https://together.jolla.com/question/61199/uitukka-seems-to-suffer-from-qtbug-39453-qml-droparea-unable-to-reject-external-drag-enter-events-droparea-broken-after-that/

**Comment by munkki84** [comment] 2014-10-30 20:41
Thanks for the feedback. I haven't updated to Uitukka, so I haven't noticed the bug. I will try to see what I can do using emulator, if I can make a workaround.

**Comment by munkki84** [comment] 2015-01-28 18:09
It's now fixed with new version.

**Closed as completed by munkki84** 2015-01-28 18:09 UTC

**Comment by ninepine** [comment] 2015-02-01 20:37
Hi

Yes the new version certainly fixes the problem. It now plays really well.

Many thanks for a great game for Sailfish.

Mike
